#####################################################################
# Project: mpaviewer dashboard
# Data:    DBCA Monitoring timeseries
# Task:    Extract data, create plots and build Shiny app
# Author:  Claude Spencer, Damon Driessen, Brooke Gibbons
# Date:    May 2026
#####################################################################

# Fresh start, clear environment
# rm(list = ls())

## Authenticate GoogleDrive and GoogleSheets ----
# options(gargle_oauth_cache = ".secrets")
## check the value of the option, if you like
# gargle::gargle_oauth_cache()
# googlesheets4::gs4_auth()

# To install Github packages (e.g. CheckEM, iLab) ----
# renv::install("iLab-fish/iLab")

# Note 1. Building and setting up the package properly ----
# Building DESCRIPTION
# DESCRIPTION provides general package metadata, lists dependencies, and is edited manually or with usethis
# usethis::use_package("ggplot2) # This will add the package to DESCRIPTION
# For Github packages, manually add them to DESCRIPTION - remotes: github

# Building NAMESPACE
# NAMESPACE manages visibility and function conflicts, defines exports, and is automatically generated by roxygen2
# For this package, most functions use the :: operator so should be fairly safe
# devtools::document() # Looks for roxygen tags to update NAMESPACE

# Building renv.lock
# For some reason some of the Github packages weren't being written properly
# I had to delete and then manually run
# renv::install("GlobalArchiveManual/CheckEM", lock = T)
# To store all the current packages to the lockfile
# renv::snapshot()

# Step 1. Load all functions from package ----
pkgload::load_all(export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)

# Set raw and project directory
# raw_dir     <- iLab::get_dir("iLab_fish", sub.folder = "!Essential_Files/Dashboard_Data") %>% # Reproducible method to get DBCA OneDrive/SharePoint
#   stringr::str_replace_all("\\\\", "/")
# project_dir <- getwd()

# Step 2. Copy all internal data from campaign sharepoint folders into dashboard data folder ----
# mpaviewer::copy_data(dir = iLab::get_dir("iLab_fish"))


# Step 3. Download all data from GoogleDrive (only run this section if it has been updated) ----
# Not sure about this section, the file doesn't exist so this won't run
# mpaviewer::googledrive_download_data(raw_dir = "C:/Users/damon/Documents/Work/Github/mpaviewer_data", project_dir = "C:/Users/damon/Documents/Work/Github/mpaviewer") # takes ~15 minutes to run

# source(paste0(project_dir, "/R/projectfolder_data_download.R"))

# Step 4. Generate new summarised data ----
# mpaviewer::generate_data(raw_dir = raw_dir)

# Step 5. Generate new plots ----
# mpaviewer:::generate_plots()

# Step 6. Run a local copy of the app for testing ----
# options("golem.app.prod" = TRUE)
mpaviewer::run_app()

# Step 6. Deploy to shiny server for testing ----
# source("secrets/creds.R") # Hidden file for marine-ecology.io credentials
# rsconnect::deployApp()

# If you break the app, check logs here
# rsconnect::showLogs(streaming = FALSE)

# Step 7. Build dockerfile ----
# mpaviewer::make_docker()

# Step 8. Test the dockerfile ---- THIS IS A WIP
# devtools::check_built("mpaviewer_0.0.0.9000.tar.gz")
