# Building a Prod-Ready, Robust Shiny Application.
#
# README: each step of the dev files is optional, and you don't have to
# fill every dev scripts before getting started.
# 01_start.R should be filled at start.
# 02_dev.R should be used to keep track of your development during the project.
# 03_deploy.R should be used once you need to deploy your app.
#
#
###################################
#### CURRENT FILE: DEV SCRIPT #####
###################################

# Engineering

## Dependencies ----
## Add one line by package you want to add as dependency
attachment::att_amend_desc()
usethis::use_package( "thinkr" )
usethis::use_package( "dplyr" )
usethis::use_package( "magrittr" )
usethis::use_package( "leaflet" )
usethis::use_package( "devtools" )
usethis::use_package( "fs" )
usethis::use_package( "here" )
usethis::use_package( "rlang" )
usethis::use_package( "ggbreak" )
usethis::use_package( "cachem")
usethis::use_package( "leaflegend")
usethis::use_package( "ggh4x")
usethis::use_package( "scales")

usethis::use_pipe()
usethis::use_data_table()
# attachment

## Add modules ----
## Create a module infrastructure in R/
golem::add_module( name = "assetmap" ) # Name of the module
golem::add_module( name = "dataloader" ) # Name of the module

## Add helper functions ----
## Creates fct_* and utils_*
golem::add_fct( "helpers" )
golem::add_utils( "helpers" )

## External resources
## Creates .js and .css files at inst/app/www
golem::add_js_file( "script" )
golem::add_js_handler( "handlers" )
golem::add_css_file( "style" )

## Add internal datasets ----
## If you have data in your package
usethis::use_data_raw( name = "corals", open = FALSE )
usethis::use_data_raw( name = "fish", open = FALSE )

## Tests ----
## Add one line by test you want to create
usethis::use_test( "app" )

# Documentation

## Vignette ----
usethis::use_vignette("mpaviewer")
devtools::build_vignettes()

## Code Coverage----
## Set the code coverage service ("codecov" or "coveralls")
usethis::use_coverage()

# Create a summary readme for the testthat subdirectory
covrpage::covrpage()

## CI ----
## Use this part of the script if you need to set up a CI
## service for your application
##
## (You'll need GitHub there)
usethis::use_github()

# GitHub Actions
usethis::use_github_actions()
# Chose one of the three
# See https://usethis.r-lib.org/reference/use_github_action.html
usethis::use_github_action_check_release()
usethis::use_github_action_check_standard()
usethis::use_github_action_check_full()
# Add action for PR
usethis::use_github_action_pr_commands()

# Travis CI
usethis::use_travis()
usethis::use_travis_badge()

# AppVeyor
usethis::use_appveyor()
usethis::use_appveyor_badge()

# Circle CI
usethis::use_circleci()
usethis::use_circleci_badge()

# Jenkins
usethis::use_jenkins()

# GitLab CI
usethis::use_gitlab_ci()

# Resources
# https://shiny.rstudio.com/articles/modules.html
# https://mastering-shiny.org/scaling-modules.html

## Authenticate GoogleDrive and GoogleSheets ----
# options(gargle_oauth_cache = ".secrets")
## check the value of the option, if you like
# gargle::gargle_oauth_cache()
# googlesheets4::gs4_auth()

# To install Github packages (e.g. CheckEM, iLab) ----
# renv::install("iLab-fish/iLab")

# Note 1. Building and setting up the package properly ----
# Building DESCRIPTION
# DESCRIPTION provides general package metadata, lists dependencies, and is edited manually or with usethis
# usethis::use_package("ggplot2) # This will add the package to DESCRIPTION
# For Github packages, manually add them to DESCRIPTION - remotes: github

# Building NAMESPACE
# NAMESPACE manages visibility and function conflicts, defines exports, and is automatically generated by roxygen2
# For this package, most functions use the :: operator so should be fairly safe
# devtools::document() # Looks for roxygen tags to update NAMESPACE

# Building renv.lock
# For some reason some of the Github packages weren't being written properly
# I had to delete and then manually run
# renv::install("GlobalArchiveManual/CheckEM", lock = T)
# To store all the current packages to the lockfile
# renv::snapshot()

# Step 1. Load all functions from package ----
pkgload::load_all(export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)

# Set raw and project directory
raw_dir     <- iLab::get_dir("iLab_fish", sub.folder = "!Essential_Files/Dashboard_Data") %>% # Reproducible method to get DBCA OneDrive/SharePoint
  stringr::str_replace_all("\\\\", "/")
project_dir <- getwd()

# Step 2. Copy all internal data from campaign sharepoint folders into dashboard data folder ----
# mpaviewer::copy_data(dir = iLab::get_dir("iLab_fish"))

# Step 3. Download all data from GoogleDrive (only run this section if it has been updated) ----
# Not sure about this section, the file doesn't exist so this won't run
# mpaviewer::googledrive_download_data(raw_dir = "C:/Users/damon/Documents/Work/Github/mpaviewer_data", project_dir = "C:/Users/damon/Documents/Work/Github/mpaviewer") # takes ~15 minutes to run

# source(paste0(project_dir, "/R/projectfolder_data_download.R"))

# Step 4. Generate new summarised data ----
# mpaviewer::generate_data(raw_dir = raw_dir)

# Step 5. Generate new plots ----
mpaviewer:::generate_plots()

# You're now set! ----
# go to dev/03_deploy.R
rstudioapi::navigateToFile("dev/03_deploy.R")
