apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpaviewer-deployment
spec:
  selector:
    matchLabels:
      app: mpaviewer-deployment
  template:
    metadata:
      labels:
        app: mpaviewer-deployment
    spec:
      containers:
        - name: mpaviewer
          image: ghcr.io/dbca-wa/mpaviewer:v0.1.0_20250807
          imagePullPolicy: IfNotPresent
          command:
            - R
            - '-e'
            - options('shiny.port'=8080,shiny.host='0.0.0.0');mpaviewer::run_app()
          volumeMounts:
            - name: mpaviewer-data-blob-prod
              mountPath: /app/inst/data
      volumes:
        - name: mpaviewer-data-blob-prod
          persistentVolumeClaim:
            claimName: pvc-mpaviewer-data-blob-prod
