apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-mpaviewer-data-blob
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-fuse-retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    volumeHandle: ecosystemsciencedata_mpaviewer-prod
    volumeAttributes:
      storageAccount: ecosystemsciencedata
      containerName: mpaviewer-prod
    nodeStageSecretRef:
      name: mpaviewer-azure-storage-secret-prod
      namespace: mpaviewer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mpaviewer-data-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  volumeName: pv-mpaviewer-data-blob-prod
  storageClassName: azureblob-fuse-retain
